# Data Preprocessing - Car Price

# Import Packages

In [1]:
# Import Packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
# Import Dataset
raw_data = pd.read_csv('Advertising.csv')
raw_data.head(11)

Unnamed: 0     TV  Radio  Newspaper  Sales
0            1  230.1   37.8       69.2   22.1
1            2   44.5   39.3       45.1   10.4
2            3   17.2   45.9       69.3    9.3
3            4  151.5   41.3       58.5   18.5
4            5  180.8   10.8       58.4   12.9
5            6    8.7   48.9       75.0    7.2
6            7   57.5   32.8       23.5   11.8
7            8  120.2   19.6       11.6   13.2
8            9    8.6    2.1        1.0    4.8
9           10  199.8    2.6       21.2   10.6
10          11   66.1    5.8       24.2    8.6

# Data Exploration

### Overview about the dataset

In [3]:
# Check total number of attributes
print("No. of Attributes (Columns): ",len(raw_data.columns))
print("No. of sample (Rows): ",len(raw_data))

No. of Attributes (Columns):  5
No. of sample (Rows):  200


In [4]:
raw_data.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [5]:
data_new = raw_data.drop(columns=raw_data.columns[0]) # to drop 1st column (Unnamed: 0), zero index based
data_new

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

# EDA

### 1. YData Profiling (Previously Pandas Profiling)

### Interactive and Comprehensive Descriptive Analysis using Pandas-Profiling

In [6]:
import ydata_profiling as pp
#Interactive and comprehensive EDA/ data description

# forming ProfileReport and save
# as output.html file
profile = pp.ProfileReport(data_new)
profile.to_file("output_raw_data.html")

D:\anaconda\Lib\site-packages\numba\core\decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
D:\anaconda\Lib\site-packages\visions\backends\shared\nan_handling.py:50: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @nb.jit


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# 2. D-Tale

D-Tale takes your Pandas dataframe to a whole new level. This powerful and fast library makes it very easy to interact with your data, carry out basic analysis and even edit it.

In [7]:
import dtale

dtale.show(data_new)

In [8]:
X = data_new.iloc[:, :-1].values
y = data_new.iloc[:, -1].values
X

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [9]:
#data partitioning (80:20) Training =80%, Testing =20%

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

In [10]:
X_train

array([[116. ,   7.7,  23.1],
       [177. ,   9.3,   6.4],
       [ 43.1,  26.7,  35.1],
       [ 62.3,  12.6,  18.3],
       [224. ,   2.4,  15.6],
       [ 38.2,   3.7,  13.8],
       [ 70.6,  16. ,  40.8],
       [147.3,  23.9,  19.1],
       [104.6,   5.7,  34.4],
       [ 76.3,  27.5,  16. ],
       [ 78.2,  46.8,  34.5],
       [168.4,   7.1,  12.8],
       [  8.7,  48.9,  75. ],
       [  7.8,  38.9,  50.6],
       [ 76.4,   0.8,  14.8],
       [129.4,   5.7,  31.3],
       [ 73.4,  17. ,  12.9],
       [289.7,  42.3,  51.2],
       [ 19.6,  20.1,  17. ],
       [197.6,   3.5,   5.9],
       [284.3,  10.6,   6.4],
       [184.9,  21. ,  22. ],
       [112.9,  17.4,  38.6],
       [ 23.8,  35.1,  65.9],
       [290.7,   4.1,   8.5],
       [ 19.4,  16. ,  22.3],
       [293.6,  27.7,   1.8],
       [ 18.7,  12.1,  23.4],
       [134.3,   4.9,   9.3],
       [ 25.6,  39. ,   9.3],
       [100.4,   9.6,   3.6],
       [ 80.2,   0. ,   9.2],
       [188.4,  18.1,  25.6],
       [17

In [11]:
# Develop model 

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred=regressor.predict(X_test)
y_pred

array([16.4080242 , 20.88988209, 21.55384318, 10.60850256, 22.11237326,
       13.10559172, 21.05719192,  7.46101034, 13.60634581, 15.15506967,
        9.04831992,  6.65328312, 14.34554487,  8.90349333,  9.68959028,
       12.16494386,  8.73628397, 16.26507258, 10.27759582, 18.83109103,
       19.56036653, 13.25103464, 12.33620695, 21.30695132,  7.82740305,
        5.80957448, 20.75753231, 11.98138077,  9.18349576,  8.5066991 ,
       12.46646769, 10.00337695, 21.3876709 , 12.24966368, 18.26661538,
       20.13766267, 14.05514005, 20.85411186, 11.0174441 ,  4.56899622])

In [13]:
import statsmodels.formula.api as sm
result = sm.ols("Sales~TV+Radio+Newspaper", data=data_new).fit()

In [14]:
#print result.summary()
print (result.rsquared, result.rsquared_adj)

0.8972106381789522 0.8956373316204668


In [15]:
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Mon, 20 Nov 2023   Prob (F-statistic):           1.58e-96
Time:                        09:21:17   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.0

In [16]:
from sklearn.metrics import mean_squared_error


print('MSE (built-in function):', round(mean_squared_error(y_test, y_pred),4))

err = np.matrix(y_test-y_pred)
print('MSE (computed):%.4f' % (err*err.T/err.shape[1]))

MSE (built-in function): 3.1741
MSE (computed):3.1741


In [17]:
# To predict new data using LR model

print(regressor.predict([[230.1,37.8,69.2]]))
print(regressor.predict([[250.1,40.8,72.2]]))
print(regressor.predict([[180.8,10.8,58.4]]))

[20.61397147]
[22.08443033]
[13.27071976]


In [18]:
print(regressor.predict([[151.5,41.3,58.5]]))

[17.73087016]
