# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
dataset.head(10)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0
5   27            58000          0
6   27            84000          0
7   32           150000          1
8   25            33000          0
9   35            65000          0

## Splitting the dataset into the Training set and Test set

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [39]:
print(X_train)

[[    36 125000]
 [    29  28000]
 [    20  36000]
 [    44 139000]
 [    56  60000]
 [    18  44000]
 [    26  15000]
 [    19  85000]
 [    19  76000]
 [    30  80000]
 [    47 107000]
 [    46  28000]
 [    40  75000]
 [    51 134000]
 [    24  27000]
 [    47  47000]
 [    27  88000]
 [    31  58000]
 [    39  71000]
 [    60  42000]
 [    50  88000]
 [    38  71000]
 [    39  61000]
 [    26  15000]
 [    21  68000]
 [    45 131000]
 [    33  31000]
 [    52  21000]
 [    30  89000]
 [    42  75000]
 [    42  80000]
 [    48 119000]
 [    31  89000]
 [    41  45000]
 [    33 113000]
 [    36  99000]
 [    26  32000]
 [    59  42000]
 [    46  79000]
 [    27  58000]
 [    35 108000]
 [    49  89000]
 [    41  72000]
 [    51 146000]
 [    23  63000]
 [    28  55000]
 [    35  75000]
 [    59  76000]
 [    34  43000]
 [    35  65000]
 [    53 104000]
 [    35  75000]
 [    39 134000]
 [    57 122000]
 [    33  51000]
 [    26  16000]
 [    40 107000]
 [    21  88000]
 [    37  7000

In [36]:
print(y_train)

[0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1
 1 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 0 1
 1 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1
 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 1 1 1 1 0
 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0
 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0
 0 1 0 0]


In [37]:
print(X_test)

[[    40  59000]
 [    38  61000]
 [    39  42000]
 [    59  42000]
 [    35  38000]
 [    53 143000]
 [    49  88000]
 [    19  26000]
 [    56 104000]
 [    35  71000]
 [    39  59000]
 [    35  77000]
 [    26  84000]
 [    31  68000]
 [    34  25000]
 [    21  72000]
 [    53  82000]
 [    29  80000]
 [    46  82000]
 [    19  19000]
 [    57 122000]
 [    47 105000]
 [    35  50000]
 [    33  60000]
 [    32  18000]
 [    20  23000]
 [    39  61000]
 [    41  52000]
 [    50  88000]
 [    49  86000]
 [    27  84000]
 [    21  88000]
 [    36  54000]
 [    36  75000]
 [    57  74000]
 [    24  89000]
 [    38 112000]
 [    46  22000]
 [    36  60000]
 [    51  23000]
 [    46  74000]
 [    53  72000]
 [    47  34000]
 [    38  51000]
 [    48  33000]
 [    37  70000]
 [    18  44000]
 [    30  80000]
 [    37  78000]
 [    35 108000]
 [    41  80000]
 [    23  28000]
 [    47  51000]
 [    48  29000]
 [    40  47000]
 [    35  27000]
 [    57  26000]
 [    22  55000]
 [    28  8400

In [42]:
print(y_test)

[1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0]


## Feature Scaling

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [44]:
print(X_train)

[[-0.13513343  1.60862427]
 [-0.80285154 -1.24866477]
 [-1.66134625 -1.01301206]
 [ 0.62797299  2.0210165 ]
 [ 1.77263261 -0.30605395]
 [-1.85212286 -0.77735936]
 [-1.08901644 -1.63160041]
 [-1.75673456  0.43036075]
 [-1.75673456  0.16525146]
 [-0.70746324  0.28307781]
 [ 0.91413789  1.07840569]
 [ 0.81874959 -1.24866477]
 [ 0.24641978  0.13579487]
 [ 1.2956911   1.87373356]
 [-1.27979305 -1.27812135]
 [ 0.91413789 -0.68898959]
 [-0.99362814  0.51873052]
 [-0.61207494 -0.36496713]
 [ 0.15103148  0.01796852]
 [ 2.15418581 -0.83627253]
 [ 1.2003028   0.51873052]
 [ 0.05564318  0.01796852]
 [ 0.15103148 -0.27659736]
 [-1.08901644 -1.63160041]
 [-1.56595795 -0.07040125]
 [ 0.72336129  1.7853638 ]
 [-0.42129833 -1.160295  ]
 [ 1.3910794  -1.45486088]
 [-0.70746324  0.5481871 ]
 [ 0.43719638  0.13579487]
 [ 0.43719638  0.28307781]
 [ 1.00952619  1.43188474]
 [-0.61207494  0.5481871 ]
 [ 0.34180808 -0.74790277]
 [-0.42129833  1.25514522]
 [-0.13513343  0.84275298]
 [-1.08901644 -1.13083841]
 

In [49]:
print(X_test)

[[ 1.4864677   0.04742511]
 [-0.03974513  0.25362122]
 [-0.51668663  1.37297157]
 [ 0.34180808 -0.33551054]
 [-0.23052173 -0.33551054]
 [ 1.581856   -0.01148807]
 [-1.18440475  0.48927393]
 [ 0.81874959 -0.33551054]
 [ 0.34180808  0.48927393]
 [-0.89823984  0.40090416]
 [ 1.6772443  -0.9246423 ]
 [-0.61207494  0.16525146]
 [ 0.34180808 -0.54170665]
 [-1.37518135 -1.48431747]
 [-0.51668663  0.45981734]
 [-0.51668663 -1.54323065]
 [-1.08901644 -0.80681595]
 [ 2.15418581  1.10786228]
 [ 0.43719638  0.28307781]
 [ 0.24641978  2.10938627]
 [-0.03974513  0.19470805]
 [ 0.81874959  0.34199099]
 [-1.08901644  0.28307781]
 [-0.61207494 -0.07040125]
 [-0.23052173  0.04742511]
 [-0.42129833 -0.80681595]
 [ 0.24641978  0.22416463]
 [-0.70746324 -1.63160041]
 [ 0.05564318  1.25514522]
 [ 0.53258468  1.72645062]
 [ 0.81874959  0.10633828]
 [ 1.2003028  -1.01301206]
 [ 0.91413789 -1.33703453]
 [ 0.24641978 -0.39442371]
 [ 0.81874959 -1.13083841]
 [-1.27979305 -0.45333689]
 [ 0.72336129  0.25362122]
 

## Training the K-NN model on the Training set

In [64]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 6, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

## Predicting a new result

In [65]:
print(classifier.predict(sc.transform([[32,150000]])))
print(classifier.predict(sc.transform([[25,33000]])))

[1]
[0]


## Predicting the Test set results

In [66]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[61  5]
 [ 5 29]]


0.9

In [59]:
# Precision & Sensitivity/Recall Report
from sklearn.metrics import classification_report
print(classification_report(y_true=y_test,y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.94      0.91      0.92        66
           1       0.83      0.88      0.86        34

    accuracy                           0.90       100
   macro avg       0.89      0.90      0.89       100
weighted avg       0.90      0.90      0.90       100

